### ISSUE TITLE
Posterior distribution methods do not work 

### ISSUE THREAD

**Issue by Asangi-a4ac** [neumanrq/ruby_stan#8]
In the code of `Stan::FitResult`, it says:

> @headers = rows[38].to_s.split(",") # In L39 there is the header column
> @data_rows = rows[43..].map { |r| r.split(",") } # From L44 on there is the raw data!

https://github.com/rstammer/cmd_stan_rb/blob/master/lib/stan/fit_result.rb#L5

However, when I tried it, it was no longer the case. Instead, the header was at L46 and raw data was from L51.

I suspect that the fundamental problem here is hardcoding the line number. Therefore, I suggest changing this to something like "Find the first row with the specific format."

**Comment by rstammer** [comment]
Hi @Asangi-a4ac - thanks for reporting this. You are right - we should not rely on the heuristically determined line number here. If you feel confident, feel free to propose a little fixing PR for it ☀️ - otherwise I'll dive in and fix within the upcoming days!

**Comment by Asangi-a4ac** [comment]
@rstammer Thank you for the reply! I will try to make a PR, but I am not good at programming so please do not expect it.

**Comment by rstammer** [comment]
Alright, @Asangi-a4ac, but nevermind  - even if you have just some parts of it, we can improve and finetune it together, so you don't need to hesitate 💪 ✌️ But of course I do not expect it, I really appreciate the reporting, too :)

**Comment by Asangi-a4ac** [comment]
@rstammer I finally finished fixing the code locally, but when I try to push it, I always get permission denied. I tried the personal access token and SSH, but both did not work. Hence, please make sure you have set your repository pushable for everyone while I try to push.
Edit: I needed to fork the repository. Now I successfully made a PR.

**Comment by rstammer** [comment]
Hey @Asangi-a4ac - I also invited you as collaborator. Happy to share access with people interested shaping it!

**Comment by Asangi-a4ac** [comment]
@rstammer Thank you for the invitation!
